{% set name = "zeroconf" %}
{% set version = "0.27.1" %}
{% set sha256 = "51a8bc581036cabcf82523c81b72f6a11b2c7913eb7eb418b6dad60cd40f9ef2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python
    - pip
  run:
    - python
    - ifaddr

test:
  imports:
    - zeroconf

about:
  home: https://github.com/jstasiak/python-zeroconf
  license: LGPL-2.1-only
  license_family: LGPL
  license_file: COPYING
  summary: A pure python implementation of multicast DNS service discovery

extra:
  recipe-maintainers:
    - abloemert
    - niecore
