{% set name = "zeroconf" %}
{% set version = "0.38.7" %}
{% set sha256 = "eaee2293e5f4e6d249f6155f9d3cca1668cb22b2545995ea72c6a03b4b7706d4" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python >=3.5
    - pip
  run:
    - python >=3.5
    - ifaddr >=0.1.7

test:
  imports:
    - zeroconf

about:
  home: https://github.com/jstasiak/python-zeroconf
  license: LGPL-2.1-only
  license_family: LGPL
  license_file: COPYING
  summary: A pure python implementation of multicast DNS service discovery

extra:
  recipe-maintainers:
    - abloemert
    - niecore
