{% set name = "zeroconf" %}
{% set version = "0.28.6" %}
{% set sha256 = "70f10f0f16e3a8c4eb5e1a106b812b8d052253041cf1ee1195933df706f5261c" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python
    - pip
  run:
    - python
    - ifaddr >=0.1.7

test:
  imports:
    - zeroconf

about:
  home: https://github.com/jstasiak/python-zeroconf
  license: LGPL-2.1-only
  license_family: LGPL
  license_file: COPYING
  summary: A pure python implementation of multicast DNS service discovery

extra:
  recipe-maintainers:
    - abloemert
    - niecore
