travis:
  secure:
    BINSTAR_TOKEN: N4N78BJ52UL+swoltaDCBAmzq+plTpAfGOTyeH5jcxnykudkMElr07v1AFC7RQkrdZ7ZwRm/137I5dRS4BJz+yQ+kwmHmueYu82HGkEbIALmDd5fpVY2lHKOT1pY4QMVGffJqAvMpeZYRZSIlZqNX9gi7vKi1iD5vS46wDupe2W7CH5OZhhyvfXU5jyBjvMo87gyE+XuEOcI7l6BB0Hka3G6uT3FByvehof2EMDM09U3pKn7c1ms2B58oZ1Z+95hb8Gy17HEhn2bcmQJlA/ZcpNYxlYZN5/UiJa6fk5VHkrBnhFpbdxmIQ2WPg11+DwrP8Thw1zMMEMqf2uLk+xE5qTyRfy1jDeIGbm0leQW7+xWuKAQOhNqHrvdoTXF45HhFL62/V1/c5nmqGZ/5xy6GjOV8pIYTQj4RWcVyFAd81ERuNO9VGDFlsL3WR3zaR5aKCPjs7yjuMKBiTQJEQ4wjNl6B1DRbEtnFDakrUa1/TKvt/muLMPwJaz6MuPvVef+2e7CTRK3Mba+QcFXXWtfh1YlOba9iXRspkFVaQ0zFrD8D9Kqg3XkpMT3hA5zxi4Udvn1qCWO60oB/1AYXD+zKW6g29fV4/AN7YVM1KfGA6Si9qzzb2c+ZuOebt9BGRo4zFgjSzxen9iTk8GNHLu82xWSIC5Pohx+4pa/ntjgGds=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
conda_forge_output_validation: true
